version: '3.8'

services:
  rtlguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtlguard-ai-app
    image: rtlguard-ai:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://kamatampadmasree56_db_user:padma22@cluster0.jnxvtay.mongodb.net/rtlguard_db?appName=Cluster0
      - SECRET_KEY=rtlguard-super-secret-key-2026
      # If using Gemini features, populate your API key below:
      - GEMINI_API_KEY=
